services: 
  nginx:
    image: nginx:alpine
    build: ./proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/proxy.conf.template:/etc/nginx/templates/default.conf.template:ro
    container_name: proxy
    depends_on:
      - frontend
      - backend
      - db

  backend: 
    image: backend
    build:
      context: ./backend
    environment:
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      FASTIFY_SECRET: ${FASTIFY_SECRET}
      FASTIFY_LOG_LEVEL: ${FASTIFY_LOG_LEVEL}
    container_name: backend
    volumes:
      - ./backend:/backend
    
  frontend: 
    image: node:alpine
    container_name: frontend
    command: sh -c "npm install && npm start"
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
  db : 
    image: database
    container_name: db
    build:
      context: ./database
    environment: 
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    #   - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dbadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./database/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  # pgdata:
  pgadmin_data:
